/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Connector.ConexionSQL;
import Interfaces.Interfaz;
import Modelo.PersonalizedExc;
import java.io.IOException;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.commons.net.examples.Main;
import Útil.PropertiesCache;

/**
 *
 * @author diego
 */
public class dgAjustes extends javax.swing.JDialog {

    Connection localConnection;

    /**
     * Creates new form dgAjustes
     */
    public dgAjustes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        btmConnect.setText(PropertiesCache.Idiomas.getString("Conectar"));
        this.setTitle(PropertiesCache.Idiomas.getString("VentanaAjustes"));
        this.setIconImage(new ImageIcon(this.getClass().getResource("/Assets/Ajustes.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIp = new javax.swing.JTextField();
        txtPuerto = new javax.swing.JTextField();
        btmConnect = new javax.swing.JButton();
        btmTest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setSize(new java.awt.Dimension(500, 400));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setText("Ip:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 100, 40, 30);

        jLabel2.setText("Host:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 150, 41, 30);
        jPanel1.add(txtIp);
        txtIp.setBounds(160, 100, 100, 30);
        jPanel1.add(txtPuerto);
        txtPuerto.setBounds(160, 150, 100, 30);

        btmConnect.setText("Conectar");
        btmConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmConnectActionPerformed(evt);
            }
        });
        jPanel1.add(btmConnect);
        btmConnect.setBounds(297, 270, 90, 24);

        btmTest.setText("Test");
        btmTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmTestActionPerformed(evt);
            }
        });
        jPanel1.add(btmTest);
        btmTest.setBounds(10, 270, 90, 24);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btmTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmTestActionPerformed
        try {
            Connection bd = ConexionSQL.getBD();
            if (txtIp.getText().isEmpty() || txtPuerto.getText().isEmpty()) {
                throw new PersonalizedExc(PropertiesCache.Idiomas.getString("DatosVacios"));
            }
            if (!ConexionSQL.Conectar(txtIp.getText(), txtPuerto.getText(), "VideoJuegos", "escritorio", "escritorio")) {
                throw new PersonalizedExc(PropertiesCache.Idiomas.getString("TestErroneo"));
            }
            JOptionPane.showMessageDialog(null, PropertiesCache.Idiomas.getString("TestCorrecto"));
            localConnection = ConexionSQL.getBD();
            ConexionSQL.setCon(bd);
        } catch (PersonalizedExc per) {
            per.GetError(per.getMessage());
        }
    }//GEN-LAST:event_btmTestActionPerformed

    private void btmConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmConnectActionPerformed
        try {
            if (!ConexionSQL.IsConected() || localConnection==null) {
                throw new PersonalizedExc(PropertiesCache.Idiomas.getString("RealizarTest"));
            }
            PropertiesCache cache = PropertiesCache.getInstance();
            cache.setProperty("ip", txtIp.getText());
            cache.setProperty("puerto", txtPuerto.getText());
            cache.flush();
            ConexionSQL.setCon(localConnection);
            dispose();
        } catch (PersonalizedExc per) {
            per.GetError(per.getMessage());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btmConnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dgAjustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dgAjustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dgAjustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dgAjustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dgAjustes dialog = new dgAjustes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmConnect;
    private javax.swing.JButton btmTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtPuerto;
    // End of variables declaration//GEN-END:variables
}
