/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Consultas.EmpresaSQL;
import Consultas.Generales;
import Consultas.GenerosSQL;
import Consultas.VideoJuegosSQL;
import Interfaces.Interfaz;
import Modelo.Empresas;
import Modelo.GeneralClass;
import Modelo.Generos;
import Modelo.PersonalizedExc;
import Modelo.VideoJuegos;
import com.github.lgooddatepicker.components.DatePicker;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Útil.PropertiesCache;

/**
 *
 * @author diego
 */
public class dgBuscador extends javax.swing.JDialog {

    /**
     * Creates new form dgBuscador
     */
    Object data[][];
    String dataNames[];
    private DefaultTableModel model = new DefaultTableModel();
    private DatePicker dateCreado = new DatePicker();
    private DatePicker dateAct = new DatePicker();
    CardLayout c;
    JPanel controlPanel;
    VideoJuegos v;
    Empresas e;
    Generos g;
    frmPadre parentFrm;

    public dgBuscador(java.awt.Frame parent, boolean modal, GeneralClass general, CardLayout card, JPanel pannel) {
        super(parent, modal);
        this.setModalityType(ModalityType.MODELESS);
        initComponents();
        if (general instanceof VideoJuegos videoJuegos) {
            String[] temp
                    = {GetString("Id"), GetString("Nombre"), GetString("Descripcion"), GetString("Genero"), GetString("Fecha_Creacion"), GetString("Fecha_Actualizacion")};
            dataNames = temp;
            v = videoJuegos;
        }
        if (general instanceof Empresas empresas) {
            String[] temp
                    = {GetString("Id"), GetString("Nombre"), GetString("Descripcion"), GetString("Fecha_Creacion"), GetString("Fecha_Actualizacion")};
            dataNames = temp;
            e = empresas;
        }
        if (general instanceof Generos generos) {
            String[] temp
                    = {GetString("Id"), GetString("Nombre"), GetString("Fecha_Creacion"), GetString("Fecha_Actualizacion")};
            dataNames = temp;
            g = generos;
        }
        jTable.setModel(new DefaultTableModel(dataNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        });
        model = (DefaultTableModel) jTable.getModel();
        pnDataPickerAct.add(dateAct);
        pnDataPickerCread.add(dateCreado);
        parentFrm = (frmPadre) parent;
        c = card;
        controlPanel = pannel;
        I18N();
    }

    public dgBuscador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btmBuscar = new javax.swing.JButton();
        btmLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        pnDataPickerAct = new javax.swing.JPanel();
        pnDataPickerCread = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jTable.setAutoCreateRowSorter(true);
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 124, 800, 480);

        btmBuscar.setText("Buscar");
        btmBuscar.setToolTipText("");
        btmBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btmBuscar);
        btmBuscar.setBounds(710, 10, 90, 24);

        btmLimpiar.setText("Limpiar");
        btmLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btmLimpiar);
        btmLimpiar.setBounds(710, 50, 90, 24);

        jLabel1.setText("Id:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 12, 13, 30);
        getContentPane().add(txtId);
        txtId.setBounds(80, 10, 90, 40);

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(21, 66, 60, 40);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(80, 64, 150, 42);
        getContentPane().add(pnDataPickerAct);
        pnDataPickerAct.setBounds(430, 64, 230, 40);
        getContentPane().add(pnDataPickerCread);
        pnDataPickerCread.setBounds(430, 10, 230, 40);

        jLabel3.setText("Actualización:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 70, 150, 40);

        jLabel4.setText("Creado:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 10, 150, 40);

        setSize(new java.awt.Dimension(816, 388));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btmLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmLimpiarActionPerformed
        txtId.setText("");
        txtNombre.setText("");
        dateAct.setText("");
        dateCreado.setText("");
        model.setRowCount(0);
    }//GEN-LAST:event_btmLimpiarActionPerformed

    private void btmBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmBuscarActionPerformed
        try {
            model.setRowCount(0);
            ArrayList<GeneralClass> list = Generales.GetBusqueda(v != null ? "VideoJuegos" : g != null ? "Géneros" : "Empresa", txtId.getText(), txtNombre.getText(), dateCreado.getDate(), dateAct.getDate());
            list.forEach((t) -> {
                if (t instanceof VideoJuegos videoJuegos) {
                    model.addRow(new Object[]{t.getId(), t.getNombre(), videoJuegos.getDescripcion(), ((VideoJuegos) t).getGenero(), t.getAuth_CreadoFecha(), t.getAuth_ActualizadoFecha()});
                } else if (t instanceof Empresas empresas) {
                    model.addRow(new Object[]{t.getId(), t.getNombre(), empresas.getDescripcion(), t.getAuth_CreadoFecha(), t.getAuth_ActualizadoFecha()});
                } else if (t instanceof Generos) {
                    model.addRow(new Object[]{t.getId(), t.getNombre(), t.getAuth_CreadoFecha(), t.getAuth_ActualizadoFecha()});
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, PropertiesCache.Idiomas.getString("ConsultaErronea"), null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btmBuscarActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        try {
            if (evt.getClickCount() > 1) {
                if (jTable.getSelectedRow() != -1) {
                    int id = (int) model.getValueAt(jTable.getSelectedRow(), 0);
                    if (v != null) {
                        parentFrm.SetVideoJuego(VideoJuegosSQL.BuscarVideoJuego("1", "Id", id + "", null).get(0));
                        c.show(controlPanel, "V");
                    }
                    if (g != null) {
                        parentFrm.SetGenero(GenerosSQL.BuscarGenero("Id", id + "", null).get(0));
                        c.show(controlPanel, "G");
                    }
                    if (e != null) {
                        parentFrm.SetEmpresa(EmpresaSQL.BuscarEmpresa("Id", id + "", null).get(0));
                        c.show(controlPanel, "E");
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(!Objects.isNull(v)) Interfaz.WindowChecker.set(0, false);
        if(!Objects.isNull(g)) Interfaz.WindowChecker.set(1, false);
        if(!Objects.isNull(e)) Interfaz.WindowChecker.set(2, false);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus

    }//GEN-LAST:event_formWindowLostFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dgBuscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dgBuscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dgBuscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dgBuscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dgBuscador dialog = new dgBuscador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmBuscar;
    private javax.swing.JButton btmLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JPanel pnDataPickerAct;
    private javax.swing.JPanel pnDataPickerCread;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private String GetString(String v) {
        return PropertiesCache.Idiomas.getString(v);
    }

    private void I18N() {
        jLabel1.setText(GetString("Id"));
        jLabel2.setText(GetString("Nombre"));
        jLabel3.setText(GetString("Fecha_Actualizacion"));
        jLabel4.setText(GetString("Fecha_Creacion"));
        btmBuscar.setText(GetString("Buscar"));
        btmLimpiar.setText(GetString("Limpiar"));
        if(!Objects.isNull(v)) this.setTitle(GetString("BuscadorV"));
        if(!Objects.isNull(g)) this.setTitle(GetString("BuscadorG"));
        if(!Objects.isNull(e)) this.setTitle(GetString("BuscadorE"));
    }

}
